### PR TITLE
GH-27 Add Worlds

### PR DESCRIPTION
**Pull request by NonSwag**
It is kinda self advertisement, but I really think this is a good addition and perfect for anyone who wants a fast, reliable and modern world management plugin for paper.
_I wouldn't be mad if this doesn't get merged because it is my project_

### CODE REVIEW

**Comment by vLuckyyy** [comment]
> It is kinda self advertisement, but I really think this is a good addition and perfect for anyone who wants a fast, reliable and modern world management plugin for paper. _I wouldn't be mad if this doesn't get merged because it is my project_

Your plugin is published under any Minecraft-plugin platform? such as Spigotmc, modrinth etc?

**Comment by NonSwag** [comment]
yes it is published on [hangar](https://hangar.papermc.io/TheNextLvl/Worlds)

**Comment by Rollczi** [comment]
Okey, please sort by alphabetical order. Despite little interest, the plugin seems to be well made. We will check the activity of the repository on github from time to time.

**Comment by NonSwag** [comment]
done :+1:

**Comment by Rollczi** [comment]
Thanks

**Pull request merged**
